name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: haskell-fido2
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: "Stylecheck"
      run: |
        nix-shell --pure --command ./bin/autoformat.sh
        git diff --exit-code

    - name: "Make sure nix files are up to date. Run `cabal2nix . > fido2.nix` if this step failed"
      run: |
        nix-shell --pure --packages cabal2nix --command "cabal2nix . > /tmp/fido2.nix.new"
        git diff --no-index fido2.nix /tmp/fido2.nix.new

    - run: nix run nixpkgs.nix-build-uncached -c nix-build-uncached
    - uses: actions/upload-artifact@v2
      with:
        name: Coverage
        path: "result/share/hpc/vanilla/html/**/*"

