name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: haskell-fido2
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: "Make sure nix files are up to date. Run `cabal2nix . > fido2.nix` if this step failed"
      run: nix-shell -p cabal2nix --command "cabal2nix . > /tmp/fido2.nix.new" && git diff --no-index fido2.nix /tmp/fido2.nix.new
    - run: nix-build
